Create unit tests as part of the api-tests ci

diff --git a/.github/workflows/api-tests.yml b/.github/workflows/api-tests.yml
--- a/.github/workflows/api-tests.yml
+++ b/.github/workflows/api-tests.yml
@@ -97,57 +97,101 @@ jobs:
       - name: Install bc
         run: apt-get update && apt-get install --yes --no-install-recommends bc
 
-      # all tests:
-      - name: Run tests and generate test coverage file (excluding tests and testutils from coverage report)
+      # unit tests:
+      - name: Run unit tests and generate test coverage file (excluding tests and testutils from coverage report)
         run: |
           set -e
           set -o pipefail
           touch poptape_admin.log
-          # go test -v -cover -coverprofile=cover.out ./tests -run '^TestListAllPoptapeStandardBuckets_FailNoS3_DEV' | tee test.out
-          go test -v ./tests/integration -cover -coverpkg=./... -coverprofile=cover.out | tee test.out
-          grep -v '/tests/' cover.out | grep -v '/testutils/' > cover.out.filtered
-          mv cover.out.filtered cover.out
+          # go test -v -cover -coverprofile=unit.cover.out ./tests/unit -run '^TestListAllPoptapeStandardBuckets_FailNoS3_DEV' 
+          go test -v ./tests/unit -cover -coverpkg=./... -coverprofile=unit.cover.out 
+          grep -v '/tests/' unit.cover.out | grep -v '/testutils/' > unit.cover.out.filtered
+          mv unit.cover.out.filtered unit.cover.out
         shell: bash
 
-      - name: Check test coverage is above threshold
+      - name: Check unit test coverage is above threshold
         env:
-          TESTCOVERAGE_THRESHOLD: 0
+          UNIT_TESTCOVERAGE_THRESHOLD: 0
         run: |
-          echo "Checking test coverage is above threshold..."
-          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
-          totalCoverage=$(go tool cover -func=cover.out | awk '/^total:/ {gsub("%","",$3); print $3}')
-          echo "Current test coverage : $totalCoverage %"
+          echo "Checking unit test coverage is above threshold..."
+          echo "Threshold             : UNIT_TESTCOVERAGE_THRESHOLD %"
+          unitTotalCoverage=$(go tool cover -func=unit.cover.out | awk '/^total:/ {gsub("%","",$3); print $3}')
+          echo "Current unit test coverage : unitTotalCoverage %"
           echo "-----------------------------------------------------------"
-          if [ "$(echo "$totalCoverage >= $TESTCOVERAGE_THRESHOLD" | bc -l)" -eq 1 ]; then
-            echo "Coverage passed threshold OK"
+          if [ "$(echo "unitTotalCoverage >= UNIT_TESTCOVERAGE_THRESHOLD" | bc -l)" -eq 1 ]; then
+            echo "Unit test coverage passed threshold OK"
           else
-            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+            echo "Current unit test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
             echo "Failed"
             exit 1
           fi
           echo "-----------------------------------------------------------"
         shell: bash
 
-      - name: Show coverage summary
-        run: go tool cover -func=cover.out
+      - name: Show unit coverage summary
+        run: go tool cover -func=unit.cover.out
 
-      - name: Generate HTML coverage report
+      - name: Generate Unit HTML coverage report
         run: |
-          go tool cover -html=cover.out -o coverage.html
+          go tool cover -html=unit.cover.out -o unit.coverage.html
 
       - name: Upload HTML coverage report
         uses: actions/upload-artifact@v4
         with:
           name: coverage-report
-          path: coverage.html
+          path: unit.coverage.html
+
+      # integration tests:
+      - name: Run integration tests and generate test coverage file (excluding tests and testutils from coverage report)
+        run: |
+          set -e
+          set -o pipefail
+          # go test -v -cover -coverprofile=int.cover.out ./tests/integration -run '^TestListAllPoptapeStandardBuckets_FailNoS3_DEV'
+          go test -v ./tests/integration -cover -coverpkg=./... -coverprofile=int.cover.out
+          grep -v '/tests/' int.cover.out | grep -v '/testutils/' > int.cover.out.filtered
+          mv int.cover.out.filtered int.cover.out
+        shell: bash
+
+      - name: Check integration test coverage is above threshold
+        env:
+          INT_TESTCOVERAGE_THRESHOLD: 0
+        run: |
+          echo "Checking integration test coverage is above threshold..."
+          echo "Threshold             : INT_TESTCOVERAGE_THRESHOLD %"
+          intTotalCoverage=$(go tool cover -func=int.cover.out | awk '/^total:/ {gsub("%","",$3); print $3}')
+          echo "Current integration test coverage : intTotalCoverage %"
+          echo "-----------------------------------------------------------"
+          if [ "$(echo "$intTotalCoverage >= INT_TESTCOVERAGE_THRESHOLD" | bc -l)" -eq 1 ]; then
+            echo "Integration test coverage passed threshold OK"
+          else
+            echo "Current integration test coverage is below threshold. Please add more integration tests or adjust threshold to a lower value."
+            echo "Failed"
+            exit 1
+          fi
+          echo "-----------------------------------------------------------"
+        shell: bash
+
+      - name: Show integration coverage summary
+        run: go tool cover -func=int.cover.out
+
+      - name: Generate Integration HTML coverage report
+        run: |
+          go tool cover -html=int.cover.out -o int.coverage.html
+
+      - name: Upload HTML coverage report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-report
+          path: int.coverage.html
 
       - name: Install gcov2lcov
         run: go install github.com/jandelgado/gcov2lcov@latest
 
-      - name: Convert Go cover.out to lcov.info
+      - name: Convert Go int.cover.out and unit.cover.out to lcov.info
         run: |
           export PATH=$PATH:$(go env GOPATH)/bin
-          gcov2lcov -infile cover.out -outfile coverage.lcov
+          gcov2lcov -infile int.cover.out -outfile int.coverage.lcov
+          gcov2lcov -infile unit.cover.out -outfile unit.coverage.lcov
 
       - name: Create coverage badges
         uses: gaelgirodon/ci-badges-action@v1
